version: "3.5"

secrets:
    transip_key:
        file: ${HOME}/secrets/transip.key

networks: 
    proxy-network:

services:
    traefik:
        hostname: traefik
        image: traefik:v2.6.1
        restart: unless-stopped
        container_name: traefik-proxy
        command:
            - --api # Secure API
            - --providers.docker # Tells Traefik to listen to docker
            - --providers.docker.exposedbydefault=false # Do not add docker services by default, but using "traefik.enable=true"
            - --providers.file.directory=/dynamic_conf # File provider
            - --entrypoints.web.address=:${PROXY_WEB_PORT}
            - --entrypoints.websecure.address=:${PROXY_WEBSECURE_PORT}
            - --certificatesresolvers.transip.acme.email=${LE_EMAIL}
            - --certificatesresolvers.transip.acme.storage=/acme.json
            - --certificatesResolvers.transip.acme.dnsChallenge.provider=transip
            - --certificatesResolvers.transip.acme.dnsChallenge.delayBeforeCheck=300
            - --certificatesresolvers.transip.acme.dnschallenge.resolvers=9.9.9.9:53,1.1.1.1:53,8.8.8.8:53
            - --serverstransport.insecureskipverify=true # Disable check for valid HTTPS certificates of backend services
            - --log.filePath=/var/log/traefik.log
        networks: 
            - proxy-network
        ports:
            - ${PROXY_WEB_PORT}:${PROXY_WEB_PORT} # HTTP
            - ${PROXY_WEBSECURE_PORT}:${PROXY_WEBSECURE_PORT} # HTTPS
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
            - ${PWD}/data/traefik/traefik.log:/var/log/traefik.log
            - ${PWD}/data/traefik/acme.json:/acme.json #certificates
            - ./traefik/dynamic_conf:/dynamic_conf #file provider
        environment:
            - TRANSIP_ACCOUNT_NAME
            - TRANSIP_PRIVATE_KEY_PATH=/run/secrets/transip_key
            - PROXY_DOMAIN # used in dynamic configuration (file provider)
            - PROXY_LOCAL_DISKSTATION
        secrets:
            - transip_key
        labels:
            # IP Whitelist
            - traefik.http.middlewares.traefik-ipwhitelist.ipwhitelist.sourcerange=${PROXY_WHITELIST:-127.0.0.1}
            # middleware redirect
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            # global redirect to https
            - traefik.http.routers.non-https.rule=hostregexp(`{host:.+}`)
            - traefik.http.routers.non-https.entrypoints=web
            - traefik.http.routers.non-https.middlewares=redirect-to-https
            # Dashboard
            - traefik.enable=true
            - traefik.http.routers.traefik.rule=Host(`traefik.${PROXY_DOMAIN}`)
            - traefik.http.routers.traefik.service=api@internal
            - traefik.http.routers.traefik.tls.certresolver=transip
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.middlewares=traefik-ipwhitelist

    unifi:
        hostname: unifi
        image: linuxserver/unifi-controller:6.5.55
        restart: unless-stopped
        container_name: unifi-controller
        networks: 
            - proxy-network
        ports:
            - 3478:3478/udp # Unifi STUN port
            - 10001:10001/udp # Required for AP discovery
            - 8080:8080 # Required for device communication
        volumes:
            - ${PWD}/data/unifi/config:/config
        environment:
            - PUID=${DOCKER_USER_ID}
            - PGID=${DOCKER_GROUP_ID}
        labels:
            - traefik.enable=true
            - traefik.http.routers.unifi.tls=true
            - traefik.http.routers.unifi.rule=Host(`unifi.${PROXY_DOMAIN}`)
            - traefik.http.routers.unifi.tls.certresolver=transip
            - traefik.http.routers.unifi.entrypoints=websecure
            - traefik.http.routers.unifi.middlewares=traefik-ipwhitelist
            - traefik.http.services.unifi.loadbalancer.server.port=8443
            - traefik.http.services.unifi.loadbalancer.server.scheme=https

    adguard:
        hostname: adguard
        image: adguard/adguardhome:v0.107.3
        restart: unless-stopped
        container_name: adguard-home
        networks: 
            - proxy-network
        ports:
            - 53:53/tcp # plain DNS
            - 53:53/udp # plain DNS
        volumes:
            - ${PWD}/data/adguard/work:/opt/adguardhome/work
            - ${PWD}/data/adguard/conf:/opt/adguardhome/conf
        labels:
            - traefik.enable=true
            - traefik.http.routers.adguard.tls=true
            - traefik.http.routers.adguard.rule=Host(`adguard.${PROXY_DOMAIN}`)
            - traefik.http.routers.adguard.tls.certresolver=transip
            - traefik.http.routers.adguard.entrypoints=websecure
            - traefik.http.routers.adguard.middlewares=traefik-ipwhitelist
            - traefik.http.services.adguard.loadbalancer.server.port=3000
            - traefik.http.services.adguard.loadbalancer.server.scheme=http
