version: "3.5"

secrets:
    cloudflare_api_token:
        file: ${PWD}/secrets/cloudflare_api_token
    google_smtp_pass:
        file: ${PWD}/secrets/google_smtp_pass
    vaultwarden_admin_token:
        file: ${PWD}/secrets/vaultwarden_admin_token
    fireflyiii_db_pass:
        file: ${PWD}/secrets/fireflyiii_db_pass
    fireflyiii_app_key:
        file: ${PWD}/secrets/fireflyiii_app_key
    fireflyiii_static_cron_token:
        file: ${PWD}/secrets/fireflyiii_static_cron_token
    
networks: 
    frontend_traefik:
        name: frontend_traefik
    backend_fireflyiii:
        name: backend_fireflyiii

services:
    traefik:
        hostname: traefik
        image: traefik:v2.10.4
        restart: unless-stopped
        container_name: traefik
        user: ${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}
        command:
            - --api # Secure API
            - --providers.docker # Tells Traefik to listen to docker
            - --providers.docker.network=frontend_traefik # Tells Traefik to use the docker network called traefik
            - --providers.docker.exposedbydefault=false # Do not add docker services by default, but using "traefik.enable=true"
            - --providers.file.directory=/homecontroller/dynamic_conf # File provider
            # HHTP entry with redirect to HTTPS
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            # HTTPS entry
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls=true
            - --entrypoints.websecure.http.tls.certresolver=cloudflare
             # Allow these IPs to set the X-Forwarded-* headers and proxyProtocol
            - --entrypoints.websecure.forwardedHeaders.trustedIPs=${PROXY_TRUSTEDIPS}
            - --entryPoints.websecure.proxyProtocol.trustedIPs=${PROXY_TRUSTEDIPS}
            # Let's encrypt with Cloudflare
            - --certificatesresolvers.cloudflare.acme.email=${LE_EMAIL}
            - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json
            - --certificatesresolvers.cloudflare.acme.caserver=${LE_CASERVER:-https://acme-v02.api.letsencrypt.org/directory}
            - --certificatesResolvers.cloudflare.acme.dnsChallenge.provider=cloudflare
            - --certificatesResolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
            - --certificatesResolvers.cloudflare.acme.dnsChallenge.delayBeforeCheck=90
            # Disable check for valid HTTPS certificates of backend services
            - --serverstransport.insecureskipverify=true
            - --log.filePath=/data/traefik.log
        networks: 
            - frontend_traefik
        ports:
            - 80:80 # HTTP
            - 443:443 # HTTPS
        secrets:
            - cloudflare_api_token
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro # docker provider
            - ${PWD}/traefik:/homecontroller # file provider
            - ${PWD}/data/traefik:/data # certificates & logs
        environment:
            - PROXY_DOMAIN # used in dynamic configuration (file provider)
            - PROXY_LOCAL_DISKSTATION # used in dynamic configuration (file provider)
            - PROXY_WEBSTATION_SUBDOMAIN=${PROXY_WEBSTATION_SUBDOMAIN:-www}
            - CLOUDFLARE_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_api_token
        labels:
            # IP Whitelist
            - traefik.http.middlewares.traefik-ipwhitelist.ipwhitelist.sourcerange=${PROXY_WHITELIST:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
            # Dashboard
            - traefik.enable=true
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.rule=Host(`traefik.${PROXY_DOMAIN}`)
            - traefik.http.routers.traefik.service=api@internal
            - traefik.http.routers.traefik.middlewares=traefik-ipwhitelist
            # wildcard certificates
            - traefik.http.routers.traefik.tls=true
            - traefik.http.routers.traefik.tls.certresolver=cloudflare
            - traefik.http.routers.traefik.tls.domains[0].main=*.${PROXY_DOMAIN}
            # default cert
            - traefik.tls.stores.default.defaultgeneratedcert.resolver=cloudflare
            - traefik.tls.stores.default.defaultgeneratedcert.domain.main=${PROXY_DOMAIN}
            - traefik.tls.stores.default.defaultgeneratedcert.domain.sans=*.${PROXY_DOMAIN}


    unifi:
        hostname: unifi
        container_name: unifi
        image: linuxserver/unifi-controller:7.5.176
        restart: unless-stopped
        depends_on:
            - traefik
        networks: 
            - frontend_traefik
        ports:
            - 3478:3478/udp # Unifi STUN port
            - 10001:10001/udp # Required for AP discovery
            - 8080:8080 # Required for device communication
        volumes:
            - ${PWD}/data/unifi/config:/config
        environment:
            - PUID=${DOCKER_USER_ID:-1000}
            - PGID=${DOCKER_GROUP_ID:-1000}
        labels:
            - traefik.enable=true
            - traefik.http.routers.unifi.rule=Host(`unifi.${PROXY_DOMAIN}`)
            - traefik.http.routers.unifi.entrypoints=websecure
            - traefik.http.routers.unifi.middlewares=traefik-ipwhitelist
            - traefik.http.services.unifi.loadbalancer.server.port=8443
            - traefik.http.services.unifi.loadbalancer.server.scheme=https

    adguard:
        hostname: adguard
        container_name: adguard
        image: adguard/adguardhome:v0.107.38
        restart: unless-stopped
        user: ${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}
        depends_on:
            - traefik
        networks: 
            - frontend_traefik
        ports:
            - 53:53/tcp # plain DNS
            - 53:53/udp # plain DNS
        volumes:
            - ${PWD}/data/adguard/work:/opt/adguardhome/work
            - ${PWD}/data/adguard/conf:/opt/adguardhome/conf
        labels:
            - traefik.enable=true
            - traefik.http.routers.adguard.rule=Host(`adguard.${PROXY_DOMAIN}`)
            - traefik.http.routers.adguard.entrypoints=websecure
            - traefik.http.routers.adguard.middlewares=traefik-ipwhitelist
            - traefik.http.services.adguard.loadbalancer.server.port=3000
            - traefik.http.services.adguard.loadbalancer.server.scheme=http

    vaultwarden:
        hostname: vaultwarden
        container_name: vaultwarden
        image: vaultwarden/server:1.29.2
        restart: unless-stopped
        user: ${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}
        depends_on:
            - traefik
        networks:
            - frontend_traefik
        environment:
            - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
            - SIGNUPS_ALLOWED=false # Disable registration of new users
            - DOMAIN=https://vaultwarden.${PROXY_DOMAIN}
            # Enable mail via Google
            - SMTP_HOST=smtp.gmail.com
            - SMTP_FROM=${GOOGLE_EMAIL}
            - SMTP_PORT=465
            - SMTP_SECURITY=force_tls
            - SMTP_USERNAME=${GOOGLE_EMAIL}
        secrets:
            - google_smtp_pass
            - vaultwarden_admin_token
        volumes:
            - ${PWD}/data/vaultwarden/data:/data
            - ${PWD}/vaultwarden/init.sh:/etc/vaultwarden.sh # script to set sensitive data via Docker secrets
        labels:
            - traefik.enable=true
            # Entry Point for UI
            - traefik.http.routers.vaultwarden-ui.service=vaultwarden-ui
            - traefik.http.routers.vaultwarden-ui.rule=Host(`vaultwarden.${PROXY_DOMAIN}`)
            - traefik.http.routers.vaultwarden-ui.entrypoints=websecure
            - traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80
            # Entry Point for Admin (with IP Whitelist)
            - traefik.http.routers.vaultwarden-admin.service=vaultwarden-admin
            - traefik.http.routers.vaultwarden-admin.rule=Host(`vaultwarden.${PROXY_DOMAIN}`) && PathPrefix(`/admin`)
            - traefik.http.routers.vaultwarden-admin.entrypoints=websecure
            - traefik.http.routers.vaultwarden-admin.middlewares=traefik-ipwhitelist
            - traefik.http.services.vaultwarden-admin.loadbalancer.server.port=80
            # Entry Point for Websocket
            - traefik.http.routers.vaultwarden-ws.service=vaultwarden-ws
            - traefik.http.routers.vaultwarden-ws.rule=Host(`vaultwarden.${PROXY_DOMAIN}`) && Path(`/notifications/hub`)
            - traefik.http.routers.vaultwarden-ws.entrypoints=websecure
            - traefik.http.services.vaultwarden-ws.loadbalancer.server.port=3012

    fireflyiii-core:
        image: fireflyiii/core:version-6.0.26
        hostname: fireflyiii-core
        container_name: fireflyiii-core
        networks:
            - backend_fireflyiii
            - frontend_traefik
        restart: unless-stopped
        volumes:
            - ${PWD}/data/fireflyiii/core:/var/www/html/storage/upload
        depends_on:
            - fireflyiii-db
            - traefik
        secrets:
            - google_smtp_pass
            - fireflyiii_db_pass
            - fireflyiii_app_key
            - fireflyiii_static_cron_token
        environment: 
            - DB_CONNECTION=pgsql
            - DB_HOST=fireflyiii-db
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD_FILE=/run/secrets/fireflyiii_db_pass
            - APP_KEY_FILE=/run/secrets/fireflyiii_app_key
            - STATIC_CRON_TOKEN_FILE=/run/secrets/fireflyiii_static_cron_token
            - SITE_OWNER=${GOOGLE_EMAIL}
            - TRUSTED_PROXIES=**
            # Enable mail via Google
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.gmail.com
            - MAIL_FROM=${GOOGLE_EMAIL}
            - MAIL_PORT=465
            - MAIL_USERNAME=${GOOGLE_EMAIL}
            - MAIL_PASSWORD_FILE=/run/secrets/google_smtp_pass
            - MAIL_ENCRYPTION=tls
        labels:
            - traefik.enable=true
            - traefik.http.routers.firefly-core.rule=Host(`firefly.${PROXY_DOMAIN}`)
            - traefik.http.routers.firefly-core.entrypoints=websecure
            - traefik.http.routers.firefly-core.middlewares=traefik-ipwhitelist
            - traefik.http.services.firefly-core.loadbalancer.server.port=8080
            - traefik.http.services.firefly-core.loadbalancer.server.scheme=http
            - traefik.docker.network=frontend_traefik

    fireflyiii-db:
        image: postgres:16.0
        hostname: fireflyiii-db
        restart: unless-stopped
        container_name: fireflyiii-db
        networks:
            - backend_fireflyiii
        secrets:
            - fireflyiii_db_pass
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/fireflyiii_db_pass
        volumes:
            - ${PWD}/data/fireflyiii/db:/var/lib/postgresql/data

    fireflyiii-importer:
        image: fireflyiii/data-importer:version-1.3.8
        hostname: fireflyiii-importer
        restart: unless-stopped
        container_name: fireflyiii-importer
        networks:
            - backend_fireflyiii
            - frontend_traefik
        depends_on:
            - fireflyiii-core
        secrets:
            - google_smtp_pass
        environment:
            - FIREFLY_III_URL=http://fireflyiii-core:8080
            - VANITY_URL=https://firefly.${PROXY_DOMAIN}
            - TRUSTED_PROXIES=**
            # Enable mail via Google
            - MAIL_HOST=smtp.gmail.com
            - MAIL_FROM_ADDRESS=${GOOGLE_EMAIL}
            - MAIL_PORT=465
            - MAIL_USERNAME=${GOOGLE_EMAIL}
            - MAIL_PASSWORD_FILE=/run/secrets/google_smtp_pass
            - MAIL_ENCRYPTION=tls
        labels:
            - traefik.enable=true
            - traefik.http.routers.firefly-importer.rule=Host(`firefly-importer.${PROXY_DOMAIN}`)
            - traefik.http.routers.firefly-importer.entrypoints=websecure
            - traefik.http.routers.firefly-importer.middlewares=traefik-ipwhitelist
            - traefik.http.services.firefly-importer.loadbalancer.server.port=8080
            - traefik.http.services.firefly-importer.loadbalancer.server.scheme=http
            - traefik.docker.network=frontend_traefik

    fireflyiii-cron:
        image: alpine:3.18.4
        container_name: fireflyiii-cron
        restart: unless-stopped
        command: sh -c "echo \"0 3 * * * wget -qO- http://fireflyiii-core:8080/api/v1/cron/$(cat /run/secrets/fireflyiii_static_cron_token)\" | crontab - && crond -f -L /dev/stdout"
        networks:
            - backend_fireflyiii
        depends_on:
            - fireflyiii-core
        secrets:
            - fireflyiii_static_cron_token