version: "3.5"

secrets:
    transip_key:
        file: ${HOME}/secrets/transip.key

networks: 
    proxy-network:

services:
    reverse-proxy:
        image: traefik:v2.3 # The official v2 Traefik docker image
        command:
            - --api.insecure=true # Enables the web UI
            - --providers.docker # Tells Traefik to listen to docker
            - --providers.docker.exposedbydefault=false # Do not add docker services by default, but using "traefik.enable=true"
            - --providers.file.directory=/dynamic_conf # File provider
            - --entrypoints.web.address=:${PROXY_WEB_PORT}
            - --entrypoints.websecure.address=:${PROXY_WEBSECURE_PORT}
            - --certificatesresolvers.transip.acme.email=${LE_EMAIL}
            - --certificatesresolvers.transip.acme.storage=/acme.json
            - --certificatesResolvers.transip.acme.dnsChallenge.provider=transip
            - --certificatesResolvers.transip.acme.dnsChallenge.delayBeforeCheck=0
            - --certificatesresolvers.transip.acme.dnschallenge.resolvers=ns0.transip.net:53,ns1.transip.nl:53,ns2.transip.eu:53,9.9.9.9:53,1.1.1.1:53,8.8.8.8:53 # Use trans IP nameservers or Quad9, Cloudflare or Google 
            - --serverstransport.insecureskipverify=true # Disable check for valid HTTPS certificates of backend sertvices
            - --log.filePath=/var/log/traefik.log
        networks: 
            - proxy-network
        ports:
            - ${PROXY_WEB_PORT}:${PROXY_WEB_PORT} # HTTP
            - ${PROXY_WEBSECURE_PORT}:${PROXY_WEBSECURE_PORT} # HTTPS
            - 8888:8080 # The Web UI (enabled by --api.insecure=true)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
            - ${PWD}/data/traefik/traefik.log:/var/log/traefik.log
            - ${PWD}/data/traefik/acme.json:/acme.json #certificates
            - ./traefik/dynamic_conf:/dynamic_conf #file provider
        environment:
            - TRANSIP_ACCOUNT_NAME
            - TRANSIP_PRIVATE_KEY_PATH=/run/secrets/transip_key
            - PROXY_DOMAIN # used in dynamic configuration (file provider)
            - PROXY_LOCAL_DISKSTATION
        secrets:
            - transip_key

    unifi:
        hostname: unifi
        image: linuxserver/unifi-controller:version-6.0.28
        networks: 
            - proxy-network
        ports:
            - 10001:10001/udp # Required for AP discovery
            - 8880:8880/tcp # Unifi guest portal HTTP redirect port
            - 8843:8843/tcp # Unifi guest portal HTTPS redirect port
            - 8443:8443/tcp # Unifi web admin port
            - 8080:8080/tcp # Required for device communication
            - 6789:6789/tcp # For mobile throughput test
            - 5514:5514/tcp # Remote syslog port
            - 3478:3478/udp # Unifi STUN port
            - 1900:1900/udp # Required for Make controller discoverable on L2 network option
        volumes:
            - ${PWD}/data/unifi/config:/config
        environment:
            - PUID=1000
            - PGID=999
        labels:
            - traefik.enable=true
            - traefik.http.routers.unifi.tls=true
            - traefik.http.routers.unifi.rule=Host(`unifi.${PROXY_DOMAIN}`)
            - traefik.http.routers.unifi.tls.certresolver=transip
            - traefik.http.routers.unifi.entrypoints=websecure
            - traefik.http.services.unifi.loadbalancer.server.port=8443
            - traefik.http.services.unifi.loadbalancer.server.scheme=https
