include:
  - ${PWD}/traefik/docker-compose.yml
  - ${PWD}/adguard/docker-compose.yml
  - ${PWD}/fireflyiii/docker-compose.yml
  - ${PWD}/unifi/docker-compose.yml
  - ${PWD}/vaultwarden/docker-compose.yml
  - ${PWD}/trala/docker-compose.yml