secrets:
    google_smtp_pass:
        file: ${PWD}/secrets/google_smtp_pass
    fireflyiii_db_pass:
        file: ${PWD}/secrets/fireflyiii_db_pass
    fireflyiii_app_key:
        file: ${PWD}/secrets/fireflyiii_app_key
    fireflyiii_static_cron_token:
        file: ${PWD}/secrets/fireflyiii_static_cron_token
    
networks: 
    frontend_traefik:
        name: frontend_traefik
    backend_fireflyiii:
        name: backend_fireflyiii

services:
    fireflyiii-core:
        image: fireflyiii/core:version-6.2.12
        hostname: fireflyiii-core
        container_name: fireflyiii-core
        networks:
            - backend_fireflyiii
            - frontend_traefik
        restart: unless-stopped
        volumes:
            - ${PWD}/data/fireflyiii/core:/var/www/html/storage/upload
        depends_on:
            - fireflyiii-db
        secrets:
            - google_smtp_pass
            - fireflyiii_db_pass
            - fireflyiii_app_key
            - fireflyiii_static_cron_token
        environment: 
            - DB_CONNECTION=pgsql
            - DB_HOST=fireflyiii-db
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD_FILE=/run/secrets/fireflyiii_db_pass
            - APP_KEY_FILE=/run/secrets/fireflyiii_app_key
            - STATIC_CRON_TOKEN_FILE=/run/secrets/fireflyiii_static_cron_token
            - SITE_OWNER=${GOOGLE_EMAIL}
            - TRUSTED_PROXIES=**
            # Enable mail via Google
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.gmail.com
            - MAIL_FROM=${GOOGLE_EMAIL}
            - MAIL_PORT=465
            - MAIL_USERNAME=${GOOGLE_EMAIL}
            - MAIL_PASSWORD_FILE=/run/secrets/google_smtp_pass
            - MAIL_ENCRYPTION=tls
        labels:
            - traefik.enable=true
            - traefik.http.routers.firefly-core.rule=Host(`firefly.${PROXY_DOMAIN}`)
            - traefik.http.routers.firefly-core.entrypoints=websecure
            - traefik.http.routers.firefly-core.middlewares=traefik-ipwhitelist
            - traefik.http.services.firefly-core.loadbalancer.server.port=8080
            - traefik.http.services.firefly-core.loadbalancer.server.scheme=http
            - traefik.docker.network=frontend_traefik

    fireflyiii-db:
        image: postgres:16.9
        hostname: fireflyiii-db
        restart: unless-stopped
        container_name: fireflyiii-db
        networks:
            - backend_fireflyiii
        secrets:
            - fireflyiii_db_pass
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/fireflyiii_db_pass
        volumes:
            - ${PWD}/data/fireflyiii/db:/var/lib/postgresql/data

    fireflyiii-importer:
        image: fireflyiii/data-importer:version-1.6.2
        hostname: fireflyiii-importer
        restart: unless-stopped
        container_name: fireflyiii-importer
        networks:
            - backend_fireflyiii
            - frontend_traefik
        depends_on:
            - fireflyiii-core
        secrets:
            - google_smtp_pass
        volumes:
            - ${PWD}/data/fireflyiii/importer:/var/www/html/storage/upload
        environment:
            - FIREFLY_III_URL=http://fireflyiii-core:8080
            - VANITY_URL=https://firefly.${PROXY_DOMAIN}
            - TRUSTED_PROXIES=**
            # Enable mail via Google
            - MAIL_HOST=smtp.gmail.com
            - MAIL_FROM_ADDRESS=${GOOGLE_EMAIL}
            - MAIL_PORT=465
            - MAIL_USERNAME=${GOOGLE_EMAIL}
            - MAIL_PASSWORD_FILE=/run/secrets/google_smtp_pass
            - MAIL_ENCRYPTION=tls
        labels:
            - traefik.enable=true
            - traefik.http.routers.firefly-importer.rule=Host(`firefly-importer.${PROXY_DOMAIN}`)
            - traefik.http.routers.firefly-importer.entrypoints=websecure
            - traefik.http.routers.firefly-importer.middlewares=traefik-ipwhitelist
            - traefik.http.services.firefly-importer.loadbalancer.server.port=8080
            - traefik.http.services.firefly-importer.loadbalancer.server.scheme=http
            - traefik.docker.network=frontend_traefik

    fireflyiii-cron:
        image: alpine:3.21.3
        container_name: fireflyiii-cron
        restart: unless-stopped
        command: sh -c "echo \"0 3 * * * wget -qO- http://fireflyiii-core:8080/api/v1/cron/$(cat /run/secrets/fireflyiii_static_cron_token)\" | crontab - && crond -f -L /dev/stdout"
        networks:
            - backend_fireflyiii
        depends_on:
            - fireflyiii-core
        secrets:
            - fireflyiii_static_cron_token