http:
  # Add a router for Synology DSM
  routers:
    nas:
      entryPoints:
        - websecure
      service: nas
      rule: Host(`nas.{{env "PROXY_DOMAIN"}}`)
      tls:
        certresolver: cloudflare
      middlewares: "redirect-mailstation"

  # rewrite for mail station
  middlewares:
    redirect-mailstation:
      redirectRegex:
        regex: "^https://nas.${PROXY_DOMAIN}/mail/(.*)"
        replacement: "http://web.${PROXY_DOMAIN}/mail/${1}"

  # Add the service for Synology DSM
  services:
    nas:
      loadBalancer:
        servers:
          - url: https://{{env "PROXY_LOCAL_DISKSTATION"}}:5001/