http:
  # Route requests for webstation, photo station, mail station etc.
  routers:
    webstation:
      entryPoints:
        - websecure
      service: webstation
      rule: Host(`{{env "PROXY_WEBSTATION_SUBDOMAIN"}}.{{env "PROXY_DOMAIN"}}`)
      tls:
        certresolver: cloudflare
        domains:
          - main: '*.{{env "PROXY_DOMAIN"}}'

  # Add a service for the Synology Diskstation
  services:
    webstation:
      loadBalancer:
        servers:
          - url: https://{{env "PROXY_LOCAL_DISKSTATION"}}/