trigger: none

variables:
  isPatch: $[eq(variables['System.PullRequest.SourceBranch'], 'refs/heads/renovate/patch')]

pool:
  name: Default

stages:
- stage: deploy
  displayName: 'Deploy Patch to TEST'
  condition: eq(variables.isPatch, true)
  jobs:
  - template: templates/deploy.yml
    parameters:
      environment: 'TEST'
      stack: 'homecontroller'

- stage: test
  displayName: 'Test patch on TEST'
  condition: and(succeeded(), eq(variables.isPatch, true))
  jobs:
  - template: templates/test.yml
    parameters:
      environment: 'TEST'
      stack: 'homecontroller'