trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README*
    - LICENSE
    - .*
    - renovate.json

pool:
  name: Default

variables:
  - group: GitHub

stages:
- stage: deploy
  displayName: 'Deploy to PROD'
  jobs:
  - template: templates/deploy.yml
    parameters:
      environment: 'PROD'
      stack: 'homecontroller'

- stage: sync
  displayName: 'Sync to GitHub'
  jobs:
  - job: SyncToGitHub
    displayName: 'Sync to GitHub'
    steps:
    - script: |
        git config --global user.email "pipeline@dev.azure.com" &&
        git config --global user.name "Azure DevOps" &&
        git clone https://$(GitHubAccessToken)@github.com/$(GitHubUserName)/$(GitHubRepository).git $(Agent.TempDirectory)/temp_repo &&
        cd $(Agent.TempDirectory)/temp_repo &&
        git checkout main &&
        tar -cpP --exclude=.git -C "$(Build.SourcesDirectory)" . | tar -xpP -C "$(Agent.TempDirectory)/temp_repo" &&
        cd $(Agent.TempDirectory)/temp_repo &&
        git add . &&
        git diff-index --quiet HEAD || git commit -m "Auto-commit from Azure DevOps" &&
        git push origin main
      displayName: 'Copy to GitHub'