trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README*
    - LICENSE
    - .*
    - renovate.json

pool:
  name: Default

variables:
  - group: GitHub

stages:
- stage: deploy
  displayName: 'Deploy to PROD'
  jobs:
  - template: templates/deploy.yml
    parameters:
      environment: 'PROD'
      stack: 'homecontroller'

- stage: sync
  displayName: 'Sync to GitHub'
  jobs:
  - job: SyncToGitHub
    displayName: 'Sync to GitHub'
    steps:
    - checkout: self

    - script: |
        git remote add github https://$(GitHubAccessToken)@github.com/$(GitHubUserName)/$(GitHubRepository).git
        git push github HEAD:main
      displayName: 'Sync to GitHub'