trigger: none

jobs:
- job: 'deploy_to_test'
  displayName: 'Deploy to TEST'
  pool: Default
  steps:
  - task: CopyFilesOverSSH@0
    displayName: 'Copy files'
    inputs:
      sshEndpoint: 'Homecontroller TEST'
      contents: |
        **
        !README*
        !LICENSE
        !.*
      targetFolder: 'homecontroller'
      readyTimeout: '20000'
  
  - task: SSH@0
    displayName: 'Run setup'
    inputs:
      sshEndpoint: 'Homecontroller TEST'
      runOptions: 'inline'
      inline: |
        cd ./homecontroller
        . ./setup.sh
      interpreterCommand: '/usr/bin/sh'
      readyTimeout: '20000'
  
  - task: SSH@0
    displayName: 'Build and start stack'
    inputs:
      sshEndpoint: 'Homecontroller TEST'
      runOptions: 'inline'
      inline: |
        cd ./homecontroller
        docker compose pull
        docker compose up -d
      interpreterCommand: '/usr/bin/sh'
      readyTimeout: '20000'