trigger: none

jobs:
- job: 'deploy_to_test'
  displayName: 'Deploy to TEST'
  pool: Default
  steps:
  - task: CopyFilesOverSSH@0
    displayName: 'Copy files'
    inputs:
      sshEndpoint: 'Homecontroller TEST'
      contents: |
        **
        !README*
        !LICENSE
        !.*
      targetFolder: 'homecontroller'
      readyTimeout: '20000'
  
  - task: SSH@0
    displayName: 'Run setup'
    inputs:
      sshEndpoint: 'Homecontroller TEST'
      runOptions: 'commands'
      commands: cd ./homecontroller && . ./setup.sh
      readyTimeout: '20000'
  
  - task: SSH@0
    displayName: 'Pull and (re)start compose stack'
    inputs:
      sshEndpoint: 'Homecontroller TEST'
      runOptions: 'commands'
      commands: 'cd ./homecontroller && docker compose pull -q 2>&1 && docker compose up -d 2>&1'
      failOnStdErr: false
      readyTimeout: '20000'